package com.example.pixabayclient.retrofit

import com.google.gson.annotations.Expose

import com.google.gson.annotations.SerializedName

//data class Post(val imageURL: String, val user: String, val likes: Int)
//
class Post {//this code was generated by jsonschema2pojo.com
    @SerializedName("total")
    @Expose
    var total: Int? = null

    @SerializedName("totalHits")
    @Expose
    var totalHits: Int? = null

    @SerializedName("hits")
    @Expose
    var hits: List<Hit>? = null

}